# coding: utf-8
"""
layout_builder.py -- Layout computation and LaTeX preamble generation
                     for the Turn2Law Branding Engine.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

from .exceptions import BrandProfileError
from .models import BrandProfile, LayoutParameters

# Turn2Law-specific asset names that must NEVER appear in a custom preamble
_T2L_ASSET_NAMES = (
    "header_decoration",
    "footer_decoration",
    "sample_asset_0_xref_36",
    "watermark_logo_n",
)


def compute_layout(
    header_h_px: Optional[int],
    footer_h_px: Optional[int],
    dpi: float,
) -> LayoutParameters:
    """
    Convert pixel image heights to PDF points and compute page margins.

    Formula: pt = px * 72 / dpi
    Top margin    = max(74, header_pt + 16)
    Bottom margin = max(66, footer_pt + 16)
    Left/right margins are fixed at 42 pt / 32 pt.
    """
    header_pt = (header_h_px * 72.0 / dpi) if header_h_px else 0.0
    footer_pt = (footer_h_px * 72.0 / dpi) if footer_h_px else 0.0
    top    = max(74.0, header_pt + 16.0)
    bottom = max(66.0, footer_pt + 16.0)
    return LayoutParameters(
        top_margin_pt    = top,
        bottom_margin_pt = bottom,
        left_margin_pt   = 42.0,
        right_margin_pt  = 32.0,
        header_height_pt = header_pt,
        footer_height_pt = footer_pt,
    )


def generate_preamble(
    profile: BrandProfile,
    layout: LayoutParameters,
    dest_path: str,
) -> str:
    """
    Generate a XeLaTeX preamble file for the given custom brand profile.

    The generated file uses FONTS_DIR_PLACEHOLDER and IMAGES_DIR_PLACEHOLDER
    so that latex_writer.py can inject absolute paths at render time.
    Image paths from the profile are written as absolute POSIX paths.

    Parameters
    ----------
    profile   : BrandProfile with processed asset paths
    layout    : LayoutParameters from compute_layout()
    dest_path : absolute path where the .tex file will be written

    Returns
    -------
    Absolute path to the written .tex file.

    Raises
    ------
    BrandProfileError
        If any Turn2Law-specific asset name leaks into the preamble.
    """
    def _posix(p: Optional[str]) -> str:
        if not p:
            return ""
        return Path(p).as_posix()

    header_path  = _posix(profile.header_image_path)
    footer_path  = _posix(profile.footer_image_path)
    wm_path      = _posix(profile.watermark_image_path)
    logo_path    = _posix(profile.logo_image_path)

    # Build conditional TikZ nodes
    bg_nodes: list[str] = []

    # Header node (always present for custom profiles)
    if header_path:
        bg_nodes.append(
            f"    \\node[anchor=north west, inner sep=0pt] at\n"
            f"      ($(current page.north west)+(0pt,0pt)$)\n"
            f"      {{\\includegraphics[width=595.5pt,height={layout.header_height_pt:.4f}pt,\n"
            f"        keepaspectratio=false]{{{header_path}}}}};"
        )

    # Footer node (optional)
    if footer_path:
        bg_nodes.append(
            f"    \\node[anchor=south west, inner sep=0pt] at\n"
            f"      ($(current page.south west)+(0pt,0pt)$)\n"
            f"      {{\\includegraphics[width=595.5pt,height={layout.footer_height_pt:.4f}pt,\n"
            f"        keepaspectratio=false]{{{footer_path}}}}};"
        )

    # Watermark node (optional) — centred at A4 midpoint with low opacity
    if wm_path:
        bg_nodes.append(
            f"    \\node[anchor=center, inner sep=0pt, opacity=0.10] at\n"
            f"      ($(current page.south west)+(297.75pt,421.13pt)$)\n"
            f"      {{\\includegraphics[width=300pt,\n"
            f"        keepaspectratio=true]{{{wm_path}}}}};"
        )

    # Logo node (optional) — top-left, same anchor as Turn2Law layout
    if logo_path:
        bg_nodes.append(
            f"    \\node[anchor=north west, inner sep=0pt] at\n"
            f"      ($(current page.north west)+(28.49pt,-32.59pt)$)\n"
            f"      {{\\includegraphics[width=200pt,height=53.5pt,\n"
            f"        keepaspectratio=true]{{{logo_path}}}}};"
        )

    bg_block = "\n".join(bg_nodes)

    tex = f"""% =============================================================================
%  brand_preamble.tex -- Custom brand preamble generated by Turn2Law
%                        Branding Engine for profile: {profile.profile_id}
%  DO NOT EDIT MANUALLY. Regenerate via resolve_preamble().
%
%  PLACEHOLDERS replaced by latex_writer.py at render time:
%    FONTS_DIR_PLACEHOLDER   -> absolute path to docgen/fonts/
%    IMAGES_DIR_PLACEHOLDER  -> absolute path to docgen/images/
% =============================================================================

\\usepackage{{fontspec}}
\\setmainfont[
  Path           = FONTS_DIR_PLACEHOLDER,
  UprightFont    = Montserrat-Regular-Full.ttf,
  BoldFont       = Montserrat-Bold-Full.ttf,
  ItalicFont     = Montserrat-Regular-Full.ttf,
  BoldItalicFont = Montserrat-Bold-Full.ttf
]{{Montserrat}}

\\newfontfamily\\garetfont[
  Path        = FONTS_DIR_PLACEHOLDER,
  UprightFont = Garet-Regular.ttf,
  BoldFont    = Garet-Bold.ttf
]{{Garet}}

\\usepackage[
  paperwidth=595.5pt,
  paperheight=842.25pt,
  top={layout.top_margin_pt:.4f}pt,
  bottom={layout.bottom_margin_pt:.4f}pt,
  left={layout.left_margin_pt:.4f}pt,
  right={layout.right_margin_pt:.4f}pt,
  noheadfoot
]{{geometry}}

\\usepackage{{graphicx}}
\\usepackage{{xcolor}}
\\usepackage{{eso-pic}}
\\usepackage{{tikz}}
\\usetikzlibrary{{calc}}
\\usepackage[absolute,overlay]{{textpos}}
\\setlength{{\\TPHorizModule}}{{1pt}}
\\setlength{{\\TPVertModule}}{{1pt}}
\\usepackage{{needspace}}
\\usepackage{{enumitem}}
\\usepackage{{array}}
\\usepackage{{ifthen}}
\\usepackage{{tabularx}}

\\setlength{{\\parindent}}{{0pt}}
\\setlength{{\\parskip}}{{5pt}}
\\linespread{{1.25}}

\\graphicspath{{{{IMAGES_DIR_PLACEHOLDER}}}}
\\pagenumbering{{gobble}}

% Colours (standard Turn2Law palette)
\\definecolor{{refgold}}{{HTML}}{{FFBD58}}
\\definecolor{{refcharcoal}}{{HTML}}{{2A2A2A}}
\\definecolor{{refdarkgold}}{{HTML}}{{B87C20}}
\\definecolor{{t2ldark}}{{HTML}}{{2A2A2A}}

% =============================================================================
%  Custom brand background -- repeats on EVERY page
% =============================================================================
\\AddToShipoutPictureBG{{%
  \\begin{{tikzpicture}}[remember picture, overlay, x=1pt, y=1pt]
{bg_block}
  \\end{{tikzpicture}}%
}}
"""

    # Write to dest_path
    Path(dest_path).parent.mkdir(parents=True, exist_ok=True)
    with open(dest_path, "w", encoding="utf-8") as fh:
        fh.write(tex)

    # After writing: scan for Turn2Law asset names; if found, delete and raise
    for bad_name in _T2L_ASSET_NAMES:
        if bad_name in tex:
            try:
                os.remove(dest_path)
            except OSError:
                pass
            raise BrandProfileError(
                f"turn2law_asset_leaked_into_custom_preamble: "
                f"Found forbidden string {bad_name!r} in generated preamble "
                f"for profile {profile.profile_id!r}. "
                "This is a bug in generate_preamble()."
            )

    return os.path.abspath(dest_path)
